language: python

python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'

install:
  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  # Replace dep1 dep2 ... with your dependencies
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION numpy nose
  - source activate test-environment
  - pip install -r requirements.txt
  - pip install --no-deps -e .
  - which nosetests

script: nosetests

deploy:
  provider: pypi
  user: CitrineInformatics
  password:
    secure: S6oBNpxWkPAQcnmyvjWt+b7JK/1HYPfXqljO+cHiG9qrtkoACqe3TqPas0iBqBSEdcpjg73MP6Ytgv3jmQKBgJBJ3ebEZncHKpqqjchFXWeRjdf432WAzDM8aVSJQYMJrJM5x6HVwyyF8+E015oJigDYsFqRNUZEOltJNmVwH2mDOH/j/H7CHY1DfNkEOWNIbtvDhO0Yw3qmuIVIC/O/48rJ5Po2vGmmxrmRhESlPPZZsBDd+PNzRd7qmJp+MEZYwpoN6x7F0Oc0Ng/Fwc2Z9tl/WmVvqqbjQswv7g7sGyQt3y19Vz9hZUmbOiclTFxWRjoF12son/J1DVjZ5dsHc6lGYfl9p5yVJb6JO64oiMcZ+jKUULz3nJdFbJ0H54VVKwEL4JW3ZuNuftmxVLj5yEcYGbNCNQNjAXtx7eEQ9Vk0eKkw1NiN64myYa/+26dq+WRsuB8KpBEmw3OckyuaH5wltwQDCSf5QmFpODAhz0uhyp0gJshBE7Kbk3xzpIEp/7/6MNquvyBlWRebWdpQFoP9/nPFtVfZu3viqsFgbKRVxu14IW79DQq/DZo+ZCYA0Gos/FvTk5h9aAI6cLeOhA95FpuybOFtPWq8rOHWZE2PxpdVUChuD7tjQxT10UhwtNANLAzhfjVxkPEIBttJyn4NBSBliKesu2sRe6GLsg0=
  on:
    distributions: sdist bdist_wheel
    repo: CitrineInformatics/pif-dft
    branch: master
