language: python

python:
- '2.7'
- '3.3'
- '3.4'
- '3.5'
- '3.6'

install:
- pip install -r requirements.txt
- python setup.py install

script: nosetests

deploy:
  provider: pypi
  user: CitrineInformatics
  password:
    secure: XC0gcTli/6dls0N4hbBQIHyl6cfgvFmZDYhmG9CJJndNZf3voXMRxB1OmAPfTrTgNowPK3fryG2NuTuvVkmlWGrykZ0HnHhyoTZyXALh1UD0HGsVd7HmjKlUj8vdmvvD6Lg/UEJeFyo7Jgb8pCyclbluBOJlX+QzbdNJa6tLF21F0bIBg3OJ/5T/FUmAKcjrGXDTJYjXnW0ofcf5aK8OQJNqhCnZ8XzqFH1IR1cBY8hQexoQmv7Z5ugDg1aqpDftAm437DmE8z/fvpv4wyecIMpz1SOPa/Rftb+wV+yiPjuGoa/xZL5gEnrJPDL3Ynf7GvRoMmkfUSW6i7kC0PVlbiofzRgXP3ZDxdl7g5uyxhJuLPiuyoaOa74plpD1k1lX6PhxHVhoAk//mvps70eZ/McL3Pj6iSvFxa58f1UcxwKIlbdf5ARGkHrmm7h91ON+QN3fL/elBnAnaGoukK/CgxfIjV2fkm3N3WIH+zyoJVVnlnWkZYK5AkeJxobpDGgw0l9jC15Kp1qrv1ANs80r+NjkIAeHkpsLJ2Fjw4ZIac8Y7m2fqG063Sedce827jpZ3nbmeOpoUtYbEkn+DQIe5bAeR+NNEb09xaDgo422VGSb9T3WI3Y1W2PQYb3ErqJUWB1gDj5Ul6y0MQqfjXlPAOb7Vgk1eV6+ANEuKov7wQw=
  on:
    distributions: sdist bdist_wheel
    repo: CitrineInformatics/pif-dft
    branch: master
