language: python
python:
  - "2.7"

# command to install dependencies
install: 
  pip install https://github.com/CitrineInformatics/pypif/zipball/master
  python setup.py install
# command to run tests
script: 
  nosetests